name: hello world

on:
  push:
      branches:
          - main
  issues:
    types:
      - opened

jobs:
    hello:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2
      - name: run echo
        run: echo "Hello, world!"

    Do-a-lil-Extra: 
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: create file in repo
          run: echo "Repository pushed! Or possibly issue created!" >> ./access.txt
        - name: Lint code
          run: pylint
